---
# defaults file for jenkins

jenkins_user: jenkins
jenkins_group: jenkins
jenkins_home: /opt/jenkins
jenkins_xms: -Xms1000m 
jenkins_xmx: -Xmx1500m

java_home: /usr/bin
java_version: java-1.8.0-openjdk


nginx_version: 1.12.2
nginx_proxy_pass: http://localhost:8080 

