---
# tasks file for nginx


- name: install nginx
  package: name=nginx state=installed     
  become: yes
  
- name: nginx version
  shell: nginx -v 2>&1 | awk -F/ '{print $2}'
  register: is_service_present


