#- name: install nginx
#  package: name=nginx state=installed
#  become: yes
#  
#- name: change nginx config
#  copy:
#    src: /opt/jenkins/nginx.conf
#    dest: /etc/nginx/nginx.conf
#    remote_src: yes
#    owner: nginx
#  become: yes
#- name: restart nginx
#  service: 
#    name: nginx
#    state: started
#    enabled: yes
#  become: yes

