

- name: PostgreSQL configuration
  become: yes
  become_user: postgres
  shell: |
    psql -c "create user "{{db_user}}""
    psql -c "alter user "{{db_user}}" with encrypted password "{{db_password}}""
    psql -c "alter role "{{db_user}}" with "{{db_user_attr}}""
    psql -c "create database "{{db_name}}" owner "{{db_owner}}""
    psql -c "grant all privileges on database "{{db_name}}" to "{{db_owner}}""
  changed_when: no

- name: change psql config
  copy: 
    src: pg_hba.conf
    dest: "{{psql_data_path}}"
    owner: "{{psql_user}}"
    group: "{{psql_user}}"

- name: ensure that postgress running and enabled
  service: 
    name: "{{psql_service}}"
    state: restarted
    enabled: yes
  





