---
# tasks file for psql

- name: install the psql rpm from a remote repo
  yum:
    name:
      - "{{link}}"      
    state: present
  become: yes
  notify: init db

- name: install the psql packages using yum
  yum:
    name:
      - "{{psql_server}}"
      - "{{psql_version}}"      
    state: present 
  become: yes

- meta: flush_handlers

- name: ensure that postgress running and enabled
  service: 
    name: "{{psql_service}}"
    state: started
    enabled: yes
  changed_when: no
  become: yes



- import_tasks: configure_db.yml


















