- hosts: all
  roles:
    - common    

- hosts: jenkins
  roles:
    - jenkins   

- hosts: sonar
  roles:    
    - sonar    
   
- hosts: nexus
  roles:
    - nexus

- hosts: tomcat
  roles:   
    - tomcat

