- hosts: all
  roles:
    - common    

- hosts: jenkins
  become: yes
  roles:
    - jenkins

- hosts: sonar
  roles:  
    - sonar    
   
- hosts: nexus
  roles:
    - nexus

- hosts: tomcat
  roles:   
    - tomcat

- hosts: control_machine
  roles:
    - deploy_tomcat

