---
# tasks file for nexus

- name: Ensure that nexus_home exist
  file: 
    path: "{{nexus_home}}"
    state: directory    

- name: Extract nexus
  unarchive:
    src: "{{link}}"
    dest: "{{nexus_home}}"
    remote_src: yes    

- name: ensure that nexus_user is owner for nexus
  file:
    path: "{{nexus_home}}"   
    recurse: yes
    state: directory
    owner: "{{nexus_user}}"
    group: "{{nexus_group}}"

- name: Deploy Systemd File nexus.service
  template:
    src: nexus.service.j2
    dest: /etc/systemd/system/nexus.service 
   
- name: start nexus
  service: 
    name: nexus
    state: started
    enabled: yes

- import_tasks: nginx_configure.yml
  when: nginx_state is changed







