---
# tasks file for java
- name: Install Java 8 using YUM.
  yum:
    name: "{{java_vers}}"
    state: present
  become: true

- name: Java Build
  shell: java -version 2>&1 | grep "Server VM .build"
  register: java_build

- name: Java version
  shell: java -version 2>&1 | awk NR==1'{print $3}'
  register: java_version
  changed_when: no
  notify:
  - save details
