---
# tasks file for jenkins

- name: Jenkins service
  copy:
    src: "{{jenkins_service}}"
    dest: "{{constant.systemd_path}}"
    owner: "{{jenkins_user}}"
    group: "{{jenkins_user}}"   
  become: yes 

- name: Start jenkins service and enable on boot
  service:
    name: "{{jenkins_service}}"
    state: started
    enabled: yes

- import_tasks: nginx_configure.yml
  when: "nginx_version in is_service_present.stdout"


