---
# tasks file for jenkins

- name: Deploy Systemd File jenkins.service
  template:
    src: jenkins.service.j2
    dest: /etc/systemd/system/jenkins.service

- name: Start jenkins service and enable on boot
  service:
    name: jenkins
    state: started
    enabled: yes

- import_tasks: nginx_configure.yml
  when: nginx_state is changed



