---
# defaults file for sonar

sonar_user: sonar
sonar_group: sonar
link: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.7.zip
sonarqube_home: /opt/sonarqube-7.7
sonarqube_conf: /opt/sonarqube-7.7/conf
xms: Xms1000m
xmx: Xmx1500m

java_home: /usr/bin
java_version: java-1.8.0-openjdk

sonar_nginx_conf: nginx.conf
nginx_owner: nginx
nginx_group: nginx
nginx_version: 1.12.2
nginx_proxy_pass: http://localhost:9000


