---
# tasks file for tomcat

- name: extract tomcat
  unarchive:
    src: "{{link}}"
    dest: /opt
    remote_src: yes   
  become: yes

- name: Deploy Systemd File tomcat.service
  template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service

- name: add tomcat manager gui and deployer user
  template:
    src: tomcat.users.xml.j2
    dest: "{{tomcat_home}}/conf/tomcat-users.xml"

- name: add ability to remote deploy
  copy:
    src: context.xml
    dest: "{{tomcat_home}}/conf/context.xml"
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"

- name: change owner for tomcat
  file:
    path: "{{tomcat_home}}"
    recurse: yes
    state: directory
    mode: 0755
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"

- name: start and enable tomcat
  service: 
    name: tomcat
    state: started
    enabled: yes

- import_tasks: nginx_configure.yml
  when: nginx_state is changed
