---
# tasks file for tomcat

- name: extract tomcat
  unarchive:
    src: "{{link}}"
    dest: /opt
    remote_src: yes   
  become: yes

- name: Deploy Systemd File tomcat.service
  template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service

- name: change owner for tomcat
  file:
    path: "{{tomcat_home}}"
    recurse: yes
    state: directory
    mode: 0755
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
  
- name: start and enable tomcat
  service: 
    name: tomcat
    state: started
    enabled: yes

- import_tasks: tomcat_configure.yml  
  notify:
  - save details

- import_tasks: nginx_configure.yml
  when: nginx_state is changed
  
