---
# tasks file for common

#- name: install common packages
#  package:
#    - name: unzip 
#      state: installed
#    - name: python-pip
#      state: installed
#    - name: git
#      state: installed
#  become: yes

- name: install common packages
  package:
    name: "{{item}}"
    state: installed
  with_items:
    - unzip     
    - python-pip      
    - git    
  become: yes
    

- pip:
    name: psycopg2
  become: yes






