---
# tasks file for common


- name: install common packages
  package:
    name: "{{item}}"
    state: installed
  with_items:
    - unzip        
    - git    
  become: yes
    
- name: Ensure Facts Directory Exists
  file:
    path: /etc/ansible/facts.d
    recurse: yes
    state: directory
  become: yes




