---
# tasks file for sonar


- name: Extract sonarqube-7.7.zip
  unarchive:
    src: "{{link}}"
    dest: /opt/
    remote_src: yes

- name: change owner for sonar
  file:
    path: "{{sonarqube_home}}"   
    recurse: yes
    state: directory
    owner: "{{sonar_user}}"
    group: "{{sonar_group}}"

- name: Deploy Systemd File sonar.service
  template:
    src: sonar.service.j2
    dest: /etc/systemd/system/sonar.service

- name: change sonar config for pgsql
  copy: 
    src: sonar.properties
    dest: "{{sonarqube_home}}/conf"
    owner: "{{sonar_user}}"
    group: "{{sonar_group}}"
    
- name: ensure that start sonar
  service: 
    name: sonar.service
    state: started
    enabled: yes
  become: yes

- import_tasks: nginx_configure.yml
  when: nginx_state is changed





