# defaults configuration

user:

  tomcat:    
    uid: 4444
    password: "{{ 'tomcat' | password_hash('sha512', 'mysecretsalt') }}"

  postgres:
    uid: 5555
    password: "{{ 'postgres' | password_hash('sha512', 'mysecretsalt') }}"

  jenkins:
    uid: 6666
    password: "{{ 'jenkins' | password_hash('sha512', 'mysecretsalt') }}" 

  sonar:   
    uid: 7777
    password: "{{ 'sonar' | password_hash('sha512', 'mysecretsalt') }}"
    
  nexus:   
    uid: 8888
    password: "{{ 'nexus' | password_hash('sha512', 'mysecretsalt') }}"
    
  nginx:   
    uid: 9999
    password: "{{ 'nginx' | password_hash('sha512', 'mysecretsalt') }}"


constant:
  systemd_path: /etc/systemd/system/
  nginx_conf_path: /etc/nginx/
  

